# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Running'), (1, 'Pending Review'), (1, 'Approved'), (1, 'Rejected')], default=0)),
                ('build_id', models.CharField(max_length=64)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_finished', models.DateTimeField(null=True)),
                ('branch_name', models.CharField(max_length=128)),
                ('pull_request_id', models.CharField(max_length=16)),
                ('commit_hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builds.Project'),
        ),
    ]
