# Generated by Django 3.0.5 on 2020-04-11 23:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_login_enabled', models.BooleanField(default=False)),
                ('google_whitelist', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('public_endpoint', models.CharField(max_length=255)),
                ('github_repo_name', models.CharField(max_length=128)),
                ('github_api_key', models.CharField(max_length=128)),
                ('auto_archive_no_diff_builds', models.BooleanField(default=True)),
                ('auto_approve_master_builds', models.BooleanField(default=True)),
                ('max_master_builds_to_keep', models.IntegerField(default=20)),
                ('max_branch_builds_to_keep', models.IntegerField(default=20)),
                ('supersede_same_branch_builds', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Initializing'), (1, 'Running'), (2, 'Finishing'), (3, 'Pending Review'), (4, 'No Diff'), (5, 'Approved'), (6, 'Rejected'), (7, 'Failed'), (8, 'Superseded'), (9, 'Failing')], default=0)),
                ('original_build_number', models.CharField(blank=True, max_length=64, null=True)),
                ('original_build_url', models.CharField(blank=True, max_length=256, null=True)),
                ('date_started', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_finished', models.DateTimeField(null=True)),
                ('date_approved', models.DateTimeField(null=True)),
                ('date_rejected', models.DateTimeField(null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=128, null=True)),
                ('branch_name', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('pull_request_id', models.CharField(blank=True, max_length=16, null=True)),
                ('commit_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='builds.Build')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='builds.Project')),
            ],
            options={
                'ordering': ('-date_started',),
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Pending'), (1, 'Matching'), (2, 'Different'), (3, 'New'), (4, 'Deleted')], default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('metadata_json', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='screenshots/')),
                ('image_diff', models.ImageField(null=True, upload_to='screenshot_diffs/')),
                ('image_diff_amount', models.FloatField(null=True)),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='builds.Build')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='builds.Screenshot')),
            ],
            options={
                'unique_together': {('build', 'name')},
            },
        ),
    ]
