# Generated by Django 4.1.8 on 2023-04-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_api_key',
            field=models.CharField(help_text='A GitHub access token.', max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_repo_name',
            field=models.CharField(help_text='owner/repo of the GitHub project.', max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Name for your project - used for display purposes.', max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='public_endpoint',
            field=models.CharField(help_text='An absolute URL to this website - used for constructing URLs to builds.', max_length=255),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
