# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_auto_20170327_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='branch_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='builds.Project'),
        ),
        migrations.AlterField(
            model_name='build',
            name='pull_request_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
