# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_auto_20170327_1953'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='build',
            unique_together=set([('project', 'build_number')]),
        ),
        migrations.AlterIndexTogether(
            name='build',
            index_together=set([]),
        ),
    ]
