# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0005_auto_20170327_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='github_repo',
            new_name='github_repo_name',
        ),
    ]
