# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0006_auto_20170327_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='screenshots/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='build',
            options={'ordering': ('-build_number',)},
        ),
        migrations.AddField(
            model_name='build',
            name='date_approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='builds.Build'),
        ),
        migrations.AlterField(
            model_name='build',
            name='commit_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='build',
            name='state',
            field=models.IntegerField(choices=[(0, 'Initializing'), (1, 'Running'), (2, 'Pending Review'), (3, 'No Diff'), (4, 'Approved'), (5, 'Rejected')], default=0),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='builds.Build'),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='builds.Screenshot'),
        ),
        migrations.AlterUniqueTogether(
            name='screenshot',
            unique_together=set([('build', 'name')]),
        ),
    ]
