# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0007_auto_20170328_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='image_diff',
            field=models.ImageField(null=True, upload_to='screenshot_diffs/'),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='state',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Matching'), (2, 'Different'), (3, 'New'), (4, 'Deleted')], default=0),
        ),
        migrations.AlterField(
            model_name='build',
            name='state',
            field=models.IntegerField(choices=[(0, 'Initializing'), (1, 'Running'), (3, 'Pending Review'), (4, 'No Diff'), (5, 'Approved'), (6, 'Rejected')], default=0),
        ),
    ]
