# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0008_auto_20170328_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='image_diff_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='state',
            field=models.IntegerField(choices=[(0, 'Initializing'), (1, 'Running'), (2, 'Finishing'), (3, 'Pending Review'), (4, 'No Diff'), (5, 'Approved'), (6, 'Rejected')], default=0),
        ),
    ]
