# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0009_auto_20170328_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='public_endpoint',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
