# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0010_project_public_endpoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='build',
            options={'ordering': ('-date_started',)},
        ),
        migrations.AddField(
            model_name='build',
            name='original_build_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='original_build_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='build',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='build',
            name='build_number',
        ),
    ]
