# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0011_auto_20170328_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='date_rejected',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
