# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0013_auto_20170329_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='metadata_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
