# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0014_screenshot_metadata_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
