# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0015_auto_20170329_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auto_archive_no_diff_builds',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='max_branch_builds_to_keep',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='project',
            name='max_master_builds_to_keep',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='build',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='build',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='builds.Build'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
