# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0016_auto_20170329_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='max_branch_builds_to_keep',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='max_master_builds_to_keep',
            field=models.IntegerField(default=20),
        ),
    ]
