# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0017_auto_20170330_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auto_approve_master_builds',
            field=models.BooleanField(default=True),
        ),
    ]
