# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0021_auto_20170404_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_login_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
