# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0022_globalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='google_whitelist',
            field=models.TextField(blank=True, null=True),
        ),
    ]
