# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0023_globalsettings_google_whitelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='state',
            field=models.IntegerField(choices=[(0, 'Initializing'), (1, 'Running'), (2, 'Finishing'), (3, 'Pending Review'), (4, 'No Diff'), (5, 'Approved'), (6, 'Rejected'), (7, 'Failed'), (8, 'Superseded')], default=0),
        ),
    ]
